config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  root to: 'rooms#index'
  resources :rooms, only: [:new, :create, :index, :destroy] do
    resources :messages, only: [:index, :create]do
      resources :user_messages, only: [:index, :create]
      resources :admin_messages, only: [:index, :create]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :users
  has_many :rooms
  has_many :messages
  has_many :admin_messages

  
  
end

app/models/admin_message.rb
class AdminMessage < ApplicationRecord
  belongs_to :admin
  belongs_to :message
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/class_name.rb
class ClassName < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'ひまわり' },
    { id: 3, name: 'さくら' },
    { id: 4, name: 'つき' },
    { id: 5, name: 'ほし' },
    { id: 6, name: 'すみれ' },
    { id: 7, name: 'モモ' },
    { id: 8, name: 'いちご' },
    { id: 9, name: 'さくらんぼ' },
    { id: 10, name: 'ドラゴンフルーツ' }
  ]

  include ActiveHash::Associations
  has_many :users
  end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  has_one :user_message, dependent: :destroy
  has_one :admin_message, dependent: :destroy
  has_one_attached :image, dependent: :destroy

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end


end

app/models/message_form_admin.rb
class MessageFormAdmin
  include ActiveModel::Model
  attr_accessor :content, :room_id, :admin_id, :image

  with_options presence: true do
    validates :content
    validates :admin_id
  end

  def save
    message = Message.create(content: content, room_id: room_id, image: image)
    AdminMessage.create(message_id: message.id, admin_id: admin_id)
  end
end

app/models/message_form_user.rb
class MessageFormUser
  include ActiveModel::Model
  attr_accessor :content, :room_id, :user_id, :image

  with_options presence: true do
    validates :content
    validates :user_id
  end

  def save
    message = Message.create(content: content, room_id: room_id, image: image)
    UserMessage.create(message_id: message.id, user_id: user_id)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  belongs_to :admin 
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,}+\z/i.freeze

  validates :password,
            format: { with: VALID_PASSWORD_REGEX, allow_blank: true }
  
  validates :class_name_id, numericality: { other_than: 1, message: "選択してください" }
  validates :children_name, presence: true
  validates :guodian_name, presence: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :class_name
  belongs_to :admin, optional: true
  has_many :rooms
  has_many :messages
  has_many :user_messages
  
end

app/models/user_message.rb
class UserMessage < ApplicationRecord
  belongs_to :user
  belongs_to :message
end

app/controllers/admin_messages_controller.rb
class AdminMessagesController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:nickname, :children_name, :guodian_name, :class_name_id, :admin_name, :admin_number])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message_form_admin = MessageFormAdmin.new
    @message_form_user = MessageFormUser.new
    @room = Room.find(params[:room_id])
    @user = @room.user
    @admin = @room.admin
    @message = @room.messages

  end
  def create
    @room = Room.find(params[:room_id])
    @admin = @room.admin_id
    @user = @room.user_id
    if admin_signed_in?
      @message_form_admin = MessageFormAdmin.new(message_form_admin_params)
      @message_form_admin.valid?
      @message_form_admin.save
      redirect_to room_messages_path(@room)
    elsif user_signed_in?
      @message_form_user = MessageFormUser.new(message_form_user_params)
      @message_form_user.valid?
      @message_form_user.save
      redirect_to room_messages_path(@room)
    else
      render :index
    end
  end

  private
  def message_form_admin_params
    params.require(:message_form_admin).permit(:content, :image).merge(admin_id: @admin, room_id: @room.id)
  end
  def message_form_user_params
    params.require(:message_form_user).permit(:content, :image).merge(user_id: @user, room_id: @room.id)
  end
 
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      redirect_to new_room_path
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end


  private

  def room_params
    params.require(:room).permit(:name, :user_id, :admin_id)
  end
end

app/controllers/user_messages_controller.rb
class UserMessagesController < ApplicationController

end

app/helpers/admin_messages_helper.rb
module AdminMessagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_messages_helper.rb
module UserMessagesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer bg-info shadow-lg">
	<div class="container text-center">
	  <p class="text-muted">©︎<?php echo $year;?> ikeda<br>
		<i class="fa-sharp fa-solid fa-map-location-dot"></i> 和歌山県⚪︎⚪︎市⚪︎⚪︎1-1-1 </p>
	</div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light p-3 shadow-sm sticky-top">
  <div class="container-fluid">
    <div class="dropdown">
      <!-- 切替ボタンの設定 -->
      <button type="button" class="btn btn-outline-bark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-list fs-3 me-1 h-1"></i>
      </button>
      <!-- ドロップメニューの設定 -->
      <ul class="dropdown-menu">
      <ul class="list-group list-group-flush" style="width: 100%;">
          <%= link_to "ホーム",rooms_path, class:"list-group-item "%>
          <%= link_to "連絡する","#", class:"list-group-item "%>
          <% if admin_signed_in? %>
            <%= link_to "お知らせ投稿","#", class:"list-group-item "%>
            <%= link_to "ルームの作成", new_room_path, class:"list-group-item "%>
          <% end %>
        </ul>
      </ul>
    </div>
    <div class="navbar-brand mb-0 ms-2 h1 fs-3 ">
       <i class="fa-sharp fa-solid fa-cat"></i>
      池田保育園
      <i class="fa-sharp fa-solid fa-cat"></i>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation" >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <% if admin_signed_in? %>
          <div class="login-name me-5">
            <%= current_admin.admin_name%>
          </div>
          <div class="logout-btn ">
            <%= link_to "ログアウト",destroy_admin_session_path, method: :delete ,class:"text-decoration-none text-reset " %>
          </div>
        <% elsif user_signed_in? %>
          <div class="login-name me-5">
            <%= current_user.children_name %>
          </div>
          <div class="logout-btn ">
            <%= link_to "ログアウト",destroy_user_session_path, method: :delete ,class:"text-decoration-none text-reset " %>
          </div>
        <% else %>
          <div class="login-btn ms-5">
            <%= link_to "ログイン",new_user_session_path ,class: "text-decoration-none text-reset " %>
          </div>
          <div class="sign-btn ms-4">
            <%= link_to "新規登録",new_user_registration_path ,class: "text-decoration-none text-reset " %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_link.html.erb
<%= if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'btn'%>
<% end %>

<%=if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: 'btn'%>
<% end %>

app/views/shared/_main_chat.html.erb
<div class="container-field bg-light pt-3 pb-4" >
  <%# ----チャット画面-------- %>
  <% if admin_signed_in?%>
    <div class="d-flex">
      <div class="btn btn-secondary  ms-2 mt-1">
      <%= link_to "ルームを削除する",  room_path(@room), method: :delete , class:"text-decoration-none text-reset"%>
      </div>
    </div>
  <% end %>
  <% if user_signed_in?%>
    <div class="d-flex">
      <div class="btn btn-secondary  ms-2 mt-1">
      <%= link_to "ホームに戻る", root_path, class:"text-decoration-none text-reset"%>
      </div>
    </div>
  <% end %>
  <div class="chat border border-5 bg-light col-7  ">
    <div class="message-field">
      <% @message.each do |message|%>
        <% unless message.admin_message.nil? %>
          <div class="create-at message d-flex flex-row- align-items-start mb-1 ">
            <%= message.admin_message.admin.admin_name%>
          </div>
          <div class="message d-flex flex-row align-items-start mb-2">
            <div class="message-icon rounded-circle bg-primary text-white fs-2">
              <i class="fa-solid fa-school"></i>
            </div><!-- right-message-icon -->
            <div class="message-text p-2 ms-2 mb-0 bg-warning">
              <%= message.admin_message.message.content%>
              <%= image_tag message.admin_message.message.image.variant(resize: '250x250'), class: 'message-image' if message.image.attached? %>
            </div><!-- .right-message-text -->
          </div><!-- .right-message -->
          <div class="create-at message d-flex flex-row- align-items-start mb-1 ">
            <%= l message.created_at %>
            </div>
        <% else message.user_message.nil? %>
          <div class="message d-flex flex-row-reverse align-items-start me-2">
           <%= message.user_message.user.children_name%>
          </div>
          <div class="message d-flex flex-row-reverse align-items-start mb-2">
            <div class="message-icon rounded-circle bg-secondary text-white fs-3">
              <i class="fas fa-user"></i>
            </div><!-- .left-message-icon -->
            <div class="message-text p-2 me-2 mb-0 bg-info">
                <%= message.user_message.message.content%>
                <%= image_tag message.user_message.message.image.variant(resize: '250x250'), class: 'message-image' if message.image.attached? %>
            </div><!-- .left-message-text -->
          </div><!-- .left-message -->
          <div class="create-at message d-flex flex-row-reverse align-items-start mb-1">
            <%= l message.created_at %>
           </div>
        <% end%>
      <% end %>
    </div>
  </div>
  <div class="message-input bg-primary col-7  mb-1">
   <% if admin_signed_in?%>
      <%= form_with model:[@room, @message_form_admin], url: room_messages_path, class:"form" , local: true do |f|%>
        <div class="form-input">
          <%= f.text_field :content, class: 'form-message', placeholder: 'メッセージを入力してください' %>
          <label class="form-image">
            <span class="image-file">画像</span>
            <%= f.file_field :image, class: 'hidden' %>
          </label>
        </div>
        <%= f.submit '送信', class: 'form-submit' %>
      <% end %>
    <% end%>
    <% if user_signed_in?%>
      <%= form_with model: [@room, @message_form_user], url: room_messages_path, class:"form" , local: true do |f|%>
        <div class="form-input">
          <%= f.text_field :content, class: 'form-message', placeholder: 'メッセージを入力してください' %>
          <label class="form-image">
            <span class="image-file">画像</span>
            <%= f.file_field :image, class: 'hidden' %>
          </label>
        </div>
        <%= f.submit '送信', class: 'form-submit' %>
      <% end %>
    <% end%>
  </div>
</div>
  <%# ----//チャット画面//-------- %>

app/views/shared/_second__error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_side_bar.html.erb
<div class="container-{breakpoint}">
  <div class="side-bar border border-3" >
    <div class="rooms">
      <div class="room p-4">
        <div class="rooms ps-2">
          <% if admin_signed_in? %>
            <% current_admin.rooms.each do |room|%>
              <div class="room-name mb-3">
                <%= link_to room.name,room_messages_path(room), class:"text-decoration-none text-reset fs-2"%>
              </div>
            <% end %>
          <% elsif user_signed_in? %>
            <% current_user.rooms.each do |room|%>
              <div class="room-name mb-3">
                <%= link_to room.name,room_messages_path(room), class:"text-decoration-none text-reset fs-2"%>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>